language: python
dist: bionic

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - pandoc
      - pandoc-citeproc

python:
  - "3.6"

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make