sudo: required
language: python
dist: bionic

addons:
  apt:
    packages:
      - texlive-full
      - pandoc
      - pandoc-citeproc

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - make