sudo: required
language: python
dist: bionic

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-lang-french
      - pandoc
      - pandoc-citeproc

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - make